Mail-Config:
  mail_sender: jjf15737314581jjf@126.com
  mail_auth_code: KVBMWYLGZYEKWQGZ
  mail_receivers:
    - 1065109432@qq.com
    - jjf15737314581jjf@126.com
  mail_host: smtp.126.com
  mail_title: 接口自动化测试报告(pytest)

Pytest-Config:
  report_title: 接口自动化测试报告(pytest)
  project_name: 测试接口
  extend01: 所属部门：软件测试
  extend02: 测试人员：jjf